import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./styles/globals.css";
import { Providers } from "../providers/providers";
import { getServerSession } from "next-auth/next";
import { authOptions } from "../lib/auth";
import { NProgressProvider } from "@/providers/NProgressProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "JEM CDYN, Dev.",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await getServerSession(authOptions);

  return (
    <html lang="en">
      <link rel="shortcut icon" href="/favicon.png?new" type="image/png" />
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <Providers session={session}>
          <NProgressProvider />
          {children}
        </Providers>
      </body>
    </html>
  );
}
